// zap.go parses go.uber.org/zap's built-in encoders, as generated by real
// zap v1.28 (see testdata/real/go):
//
//   - development console (zap.NewDevelopment): "<ISO8601 -0700 ts>\tERROR\t
//     <caller>\t<msg>\t<json fields>", then the log call site's stack
//     ("main.main\n\t/path/main.go:78\n...") on the following lines;
//   - production console (Encoding "console"): the same columns with a
//     float epoch ts ("1.790137826326494e+09") and a lower-case level;
//   - production JSON: {"level":"error","ts":1790137826.33,"caller":...,
//     "msg":...,"error":...,"errorVerbose":...,"stacktrace":...}.
//
// zap.Error(err) on a github.com/pkg/errors error adds an "errorVerbose"
// field holding the error's "%+v" rendering, which is where the error's
// ORIGIN is ("stacktrace" is only the log call site), and sugar's
// Errorf("%+v", err) prints the same rendering raw after the entry line.
// pkg/errors "%+v" prints the root error first -- "<message>" then, per
// frame, "<func>\n\t<file>:<line>" down to runtime.goexit -- followed by
// each wrapping layer ("<message>" + its own stack). The parser turns the
// last (outermost) layer into Frames and the earlier layers into Chained,
// innermost last; without errorVerbose it falls back to the call-site
// stack, and with no stack at all the entry is a message-only event.
//
// monitor imports neither zap nor pkg/errors; these are text shapes.
package stacktrace

import (
	"encoding/json"
	"regexp"
	"strings"
)

var (
	// zap console entry: timestamp (ISO8601 with Z / ±hh:mm / ±hhmm, or
	// an epoch in seconds/millis/nanos: "1790137826.33",
	// "1.790137826326494e+09"), a tab, the level word in either case, a
	// tab.
	reZapConsole = regexp.MustCompile(`^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?|\d{9,}(?:\.\d+)?|\d\.\d+[eE][+-]?\d+)\t(?i:(debug|info|warn|warning|error|dpanic|panic|fatal))\t`)
	// zap's caller column ("svc/handler.go:42").
	reZapCaller = regexp.MustCompile(`^\S+\.go:\d+$`)
	// pkg/errors / zap stack lines.
	rePkgErrorsFile = regexp.MustCompile(`^\t(\S+):(\d+)$`)
	reGoFuncToken   = regexp.MustCompile(`^[A-Za-z_][^\s:]*\.[^\s:]+$`)
)

// zapConsoleLevel returns the level word of a zap console entry, or "".
func zapConsoleLevel(line string) string {
	m := reZapConsole.FindStringSubmatch(line)
	if m == nil {
		return ""
	}
	return m[2]
}

// zapJSONEntry decodes a zap JSON entry: an object with a string level
// ("level", or "L" for the development key names), a string message ("msg"
// / "M") and a timestamp ("ts" / "T"). Logs from other JSON loggers (winston
// and structlog use "message"/"event", pino and bunyan use numeric levels)
// are not zap and return nil.
func zapJSONEntry(line string) map[string]any {
	line = strings.TrimSpace(line)
	if !strings.HasPrefix(line, "{") || !strings.HasSuffix(line, "}") {
		return nil
	}
	if !strings.Contains(line, `"level"`) && !strings.Contains(line, `"L"`) {
		return nil
	}
	var m map[string]any
	if err := json.Unmarshal([]byte(line), &m); err != nil {
		return nil
	}
	lvl, _ := firstString(m, "level", "L")
	_, hasMsg := firstString(m, "msg", "M")
	_, hasTS := m["ts"]
	if _, ok := m["T"]; ok {
		hasTS = true
	}
	if !hasMsg || !hasTS || !isZapLevel(lvl) {
		return nil
	}
	return m
}

func zapJSONLevel(line string) string {
	m := zapJSONEntry(line)
	if m == nil {
		return ""
	}
	lvl, _ := firstString(m, "level", "L")
	return lvl
}

func isZapLevel(s string) bool {
	switch strings.ToLower(s) {
	case "debug", "info", "warn", "warning", "error", "dpanic", "panic", "fatal":
		return true
	}
	return false
}

func firstString(m map[string]any, keys ...string) (string, bool) {
	for _, k := range keys {
		if v, ok := m[k].(string); ok {
			return v, true
		}
	}
	return "", false
}

func zapStarts(level string) bool {
	_, ok := levelFromLogPrefix(level)
	return ok
}

var zapConsoleRule = blockRule{
	kind:  "zap-console",
	start: func(line string) bool { return zapStarts(zapConsoleLevel(line)) },
	open:  func(string) grammar { return &pkgErrorsGrammar{} },
}

var zapJSONRule = blockRule{
	kind:  "zap-json",
	start: func(line string) bool { return zapStarts(zapJSONLevel(line)) },
	open:  func(string) grammar { return &pkgErrorsGrammar{} },
}

// pkgErrorsGrammar continues a zap entry only with lines shaped like a
// pkg/errors "%+v" trace or zap's own call-site stack: "<func>" +
// "\t<file>:<line>" pairs and the message lines between layers. Func and
// message lines are tentative until a "\t<file>:<line>" line confirms them,
// so anything else -- a zap info line, a panic, a JS error -- ends the
// entry without being swallowed.
type pkgErrorsGrammar struct {
	afterFunc bool
	messages  int
}

func (g *pkgErrorsGrammar) next(line string, boundary bool) verdict {
	if boundary || strings.TrimSpace(line) == "" {
		return vReject
	}
	if rePkgErrorsFile.MatchString(line) {
		if !g.afterFunc {
			return vReject
		}
		g.afterFunc, g.messages = false, 0
		return vAccept
	}
	if reGoFuncToken.MatchString(line) {
		g.afterFunc = true
		return vTentative
	}
	if isIndented(line) {
		return vReject
	}
	// A layer message ("load failed") between two stacks.
	g.afterFunc = false
	g.messages++
	if g.messages > 3 {
		return vReject
	}
	return vTentative
}

// pkgSegment is one layer of a pkg/errors "%+v" rendering (or zap's
// call-site stack, which has no message and never includes runtime.goexit).
type pkgSegment struct {
	msg    string
	hasMsg bool
	frames []Frame // as printed: deepest first
	goexit bool
}

// splitPkgErrors splits trace lines into layers: a message line starts a
// new layer, and so does the first frame after a layer that ended in
// runtime.goexit (pkg/errors stacks always do; zap's call-site stack never
// does).
func splitPkgErrors(lines []string) []pkgSegment {
	var segs []pkgSegment
	cur := -1
	for i := 0; i < len(lines); i++ {
		l := lines[i]
		if strings.TrimSpace(l) == "" {
			continue
		}
		if reGoFuncToken.MatchString(l) && i+1 < len(lines) {
			if m := rePkgErrorsFile.FindStringSubmatch(lines[i+1]); m != nil {
				if cur < 0 || segs[cur].goexit {
					segs = append(segs, pkgSegment{})
					cur = len(segs) - 1
				}
				segs[cur].frames = append(segs[cur].frames, goFrame(l, m[1], m[2]))
				if l == "runtime.goexit" {
					segs[cur].goexit = true
				}
				i++
				continue
			}
		}
		if rePkgErrorsFile.MatchString(l) || isIndented(l) {
			continue
		}
		segs = append(segs, pkgSegment{msg: l, hasMsg: true})
		cur = len(segs) - 1
	}
	return segs
}

// applyZapTrace fills ex.Frames/ex.Chained from the error's pkg/errors
// layers (errorVerbose, or a trace printed after the entry line), falling
// back to zap's call-site stack (the raw lines after the entry, or the JSON
// "stacktrace" field).
func applyZapTrace(ex *Exception, verbose string, raw []string, stack string) {
	var layers []pkgSegment
	var callSite []Frame
	if verbose != "" {
		for _, s := range splitPkgErrors(strings.Split(verbose, "\n")) {
			if len(s.frames) > 0 {
				layers = append(layers, s)
			}
		}
	}
	for idx, s := range splitPkgErrors(raw) {
		if len(s.frames) == 0 {
			continue
		}
		if s.hasMsg || s.goexit {
			// An error layer printed after the entry line. A
			// message-less first layer reaching runtime.goexit is a
			// "%+v" rendering that started inside the entry's own
			// message (sugar Errorf("...: %+v", err)).
			if verbose == "" {
				if !s.hasMsg && idx == 0 {
					s.msg = ex.Value
				}
				layers = append(layers, s)
			}
			continue
		}
		callSite = s.frames
	}
	if stack != "" && callSite == nil {
		for _, s := range splitPkgErrors(strings.Split(stack, "\n")) {
			if len(s.frames) > 0 {
				callSite = s.frames
				break
			}
		}
	}
	switch {
	case len(layers) > 0:
		outer := layers[len(layers)-1]
		ex.Frames = reversedCopy(outer.frames)
		for i := len(layers) - 2; i >= 0; i-- {
			ex.Chained = append(ex.Chained, Exception{Value: layers[i].msg, Frames: reversedCopy(layers[i].frames)})
		}
	case len(callSite) > 0:
		ex.Frames = reversedCopy(callSite)
	}
}

func reversedCopy(f []Frame) []Frame {
	out := append([]Frame(nil), f...)
	reverseFrames(out)
	return out
}

func zapException(block Block, levelTok, msg string) *Exception {
	level, ok := levelFromLogPrefix(levelTok)
	if !ok {
		return nil
	}
	return &Exception{
		Runtime:   "go",
		Parser:    "zap",
		Value:     msg,
		Level:     level,
		Handled:   boolPtr(level != LevelFatal),
		LineStart: block.LineStart,
		LineEnd:   block.LineEnd,
	}
}

// finishZap applies the message-only rule and the chain inheritance.
func finishZap(ex *Exception) *Exception {
	if len(ex.Frames) == 0 {
		ex.Parser = "message"
		ex.Chained = nil
	}
	inheritChain(ex)
	return ex
}

func parseZapConsole(block Block) *Exception {
	cols := strings.Split(block.Lines[0], "\t")
	if len(cols) < 3 {
		return nil
	}
	ts, levelTok := cols[0], cols[1]
	rest := cols[2:]
	// A trailing JSON fields column.
	var fields map[string]any
	if n := len(rest); n > 1 && strings.HasPrefix(rest[n-1], "{") && json.Unmarshal([]byte(rest[n-1]), &fields) == nil {
		rest = rest[:n-1]
	}
	// Optional logger-name and caller columns before the message: the
	// message follows the caller when there is one, else it is the last
	// remaining column (a Named logger without WithCaller prints
	// "<ts>\tERROR\tapi\t<msg>").
	msgAt := len(rest) - 1
	for i := 0; i < len(rest)-1 && i < 2; i++ {
		if reZapCaller.MatchString(rest[i]) {
			msgAt = i + 1
			break
		}
	}
	if msgAt < 0 {
		return nil
	}
	msg := strings.Join(rest[msgAt:], "\t")
	ex := zapException(block, levelTok, msg)
	if ex == nil {
		return nil
	}
	if t, ok := parseAnyTimestamp(ts, block.Location); ok {
		ex.ObservedAt = t
	}
	verbose, _ := firstString(fields, "errorVerbose")
	stack, _ := firstString(fields, "stacktrace")
	applyZapTrace(ex, verbose, block.Lines[1:], stack)
	return finishZap(ex)
}

func parseZapJSON(block Block) *Exception {
	m := zapJSONEntry(block.Lines[0])
	if m == nil {
		return nil
	}
	lvl, _ := firstString(m, "level", "L")
	msg, _ := firstString(m, "msg", "M")
	ex := zapException(block, lvl, msg)
	if ex == nil {
		return nil
	}
	for _, k := range []string{"ts", "T"} {
		switch v := m[k].(type) {
		case float64:
			if t, ok := parseEpoch(jsonNumber(v)); ok {
				ex.ObservedAt = t
			}
		case string:
			if t, ok := parseAnyTimestamp(v, block.Location); ok {
				ex.ObservedAt = t
			}
		}
		if !ex.ObservedAt.IsZero() {
			break
		}
	}
	verbose, _ := firstString(m, "errorVerbose")
	stack, _ := firstString(m, "stacktrace", "S")
	applyZapTrace(ex, verbose, block.Lines[1:], stack)
	return finishZap(ex)
}

func jsonNumber(f float64) string {
	b, _ := json.Marshal(f)
	return string(b)
}
